using System.Net;
using System.Net.Sockets;
using FluentAssertions;
using MessagePack;
using Microsoft.Extensions.Logging.Abstractions;
using Skynet.Cluster;
using Skynet.Core;
using Skynet.Core.Serialization;
using Xunit;

namespace Skynet.Core.Tests;

public sealed class KcpTransportTests
{
	[Fact]
	public async Task CallAsync_ShouldRoundtripAcrossKcpNodes()
	{
		var configuration = CreateConfiguration(GetFreeUdpPort(), GetFreeUdpPort());

		await using var system1 = CreateSystem(configuration, "node1");
		await system1.CreateActorAsync(() => new KcpEchoActor(), "echo",
			new ActorCreationOptions { HandleOverride = new ActorHandle(1001) });

		await using var system2 = CreateSystem(configuration, "node2");

		var remote = system2.GetByName("echo");
		var result = await remote.CallAsync<string>(new KcpEchoRequest("ping"), TimeSpan.FromSeconds(10));

		result.Should().Be("echo:pong");
	}

	[Fact]
	public async Task SendAsync_ShouldDeliverPlainObjectPayloadAcrossKcpNodes()
	{
		var configuration = CreateConfiguration(GetFreeUdpPort(), GetFreeUdpPort());

		await using var system1 = CreateSystem(configuration, "node1");
		await system1.CreateActorAsync(() => new KcpRecordingActor(), "recorder",
			new ActorCreationOptions { HandleOverride = new ActorHandle(1001) });

		await using var system2 = CreateSystem(configuration, "node2");

		var remote = system2.GetByName("recorder");
		await system2.SendAsync(remote.Handle, new KcpEchoRequest("fire"));

		// Fire-and-forget: poll the remote actor until the plain object payload has arrived.
		for (var attempt = 0; attempt < 100; attempt++)
		{
			var last = await remote.CallAsync<string>(new KcpGetLastMessage(), TimeSpan.FromSeconds(2));
			if (last == "fire")
			{
				return;
			}

			await Task.Delay(50);
		}

		throw new InvalidOperationException("The plain object payload was never delivered to the remote actor.");
	}

	[Fact]
	public async Task RpcProxy_ShouldRoundtripAcrossKcpNodes()
	{
		var configuration = CreateConfiguration(GetFreeUdpPort(), GetFreeUdpPort());

		await using var system1 = CreateSystem(configuration, "node1");
		await system1.CreateActorAsync(() => new KcpEchoRpcActor(), "echoRpc",
			new ActorCreationOptions { HandleOverride = new ActorHandle(1001) });

		await using var system2 = CreateSystem(configuration, "node2");

		// The proxy serializes request payload types generated by the source generator; the remote
		// side must resolve them through the contract id table instead of reflection.
		var proxy = system2.GetService<IKcpEchoRpc>("echoRpc");
		var echo = await proxy.EchoAsync("ping");
		echo.Should().Be("echo:ping");

		var info = await proxy.GetInfoAsync(new KcpPongRequest(21));
		info.Doubled.Should().Be(42);
		info.Source.Should().Be("kcp-rpc");
	}

	private static KcpTransportOptions CreateTestOptions()
	{
		return new KcpTransportOptions
		{
			HeartbeatInterval = TimeSpan.FromMilliseconds(250),
			IntervalMilliseconds = 10
		};
	}

	private static ActorSystem CreateSystem(StaticClusterConfiguration configuration, string nodeId)
	{
		var registry = new StaticClusterRegistry(configuration, nodeId);
		return new ActorSystem(
			options: new ActorSystemOptions { ClusterRegistry = registry },
			transportFactory: sys => new KcpTransport(sys, registry, CreateTestOptions(),
				NullLoggerFactory.Instance));
	}

	private static StaticClusterConfiguration CreateConfiguration(int port1, int port2)
	{
		return new StaticClusterConfiguration
		{
			Nodes = new[]
			{
				new StaticClusterNodeConfiguration
				{
					NodeId = "node1",
					Host = "127.0.0.1",
					Port = port1,
					HandleOffset = 1000,
					Services = new Dictionary<string, long>(StringComparer.Ordinal)
					{
						["echo"] = 1001,
						["recorder"] = 1001,
						["echoRpc"] = 1001
					}
				},
				new StaticClusterNodeConfiguration
				{
					NodeId = "node2",
					Host = "127.0.0.1",
					Port = port2,
					HandleOffset = 2000,
					Services = new Dictionary<string, long>(StringComparer.Ordinal)
				}
			}
		};
	}

	private static int GetFreeUdpPort()
	{
		using var client = new UdpClient(0, AddressFamily.InterNetwork);
		return ((IPEndPoint)client.Client.LocalEndPoint!).Port;
	}

	private sealed class KcpEchoActor : Actor
	{
		protected override Task<object?> ReceiveAsync(MessageEnvelope envelope, CancellationToken cancellationToken)
		{
			return envelope.Payload switch
			{
				KcpEchoRequest request => Task.FromResult<object?>("echo:" +
					request.Message.Replace("ping", "pong", StringComparison.Ordinal)),
				_ => Task.FromResult<object?>(null)
			};
		}
	}

	private sealed class KcpRecordingActor : Actor
	{
		private string? _lastMessage;

		protected override Task<object?> ReceiveAsync(MessageEnvelope envelope, CancellationToken cancellationToken)
		{
			switch (envelope.Payload)
			{
				case KcpEchoRequest request:
					_lastMessage = request.Message;
					return Task.FromResult<object?>(null);
				case KcpGetLastMessage:
					return Task.FromResult<object?>(_lastMessage);
				default:
					return Task.FromResult<object?>(null);
			}
		}
	}

	private sealed class KcpEchoRpcActor : RpcActor<IKcpEchoRpc>, IKcpEchoRpc
	{
		public Task<string> EchoAsync(string message, CancellationToken cancellationToken = default)
		{
			return Task.FromResult("echo:" + message);
		}

		public Task<KcpPongResponse> GetInfoAsync(KcpPongRequest request, CancellationToken cancellationToken = default)
		{
			return Task.FromResult(new KcpPongResponse(request.Value * 2, "kcp-rpc"));
		}
	}

	[MessagePackObject(AllowPrivate = true)]
	internal sealed record KcpGetLastMessage;

	[MessagePackObject(AllowPrivate = true)]
	internal sealed record KcpEchoRequest([property: Key(0)] string Message);
}

[SkynetActor("echoRpc")]
public interface IKcpEchoRpc
{
	Task<string> EchoAsync(string message, CancellationToken cancellationToken = default);

	Task<KcpPongResponse> GetInfoAsync(KcpPongRequest request, CancellationToken cancellationToken = default);
}

[MessagePackObject]
public sealed record KcpPongRequest([property: Key(0)] int Value);

[MessagePackObject]
public sealed record KcpPongResponse([property: Key(0)] int Doubled, [property: Key(1)] string Source);
